@user1 = User.create!(first_name: "Admin", last_name: "Guest", email: "admin_guest@example.com", birthdate: "2022-07-06 00:00:00", gender: "male", password: "123456", password_confirmation: "123456", admin: true)
@user2 = User.create!(first_name: "Guest", last_name: "User", email: "guest@example.com", birthdate: "2022-07-06 00:00:00", gender: "male", password: "123456", password_confirmation: "123456")
@user3 = User.create!(first_name: "test_first3", last_name: "test_last3", email: "test3@gmail.com", birthdate: "2022-07-06 00:00:00", gender: "male", password: "123456", password_confirmation: "123456")
@user4 = User.create!(first_name: "test_first4", last_name: "test_last4", email: "test4@gmail.com", birthdate: "2022-07-06 00:00:00", gender: "male", password: "123456", password_confirmation: "123456")
@user5 = User.create!(first_name: "test_first5", last_name: "test_last5", email: "test5@gmail.com", birthdate: "2022-07-06 00:00:00", gender: "male", password: "123456", password_confirmation: "123456")

@post1 = Post.create!(title: "test1", body: "content1", user_id: @user1.id)
@post2 = Post.create!(title: "test2", body: "content2", user_id: @user2.id)
@post3 = Post.create!(title: "test3", body: "content3", user_id: @user3.id)
@post4 = Post.create!(title: "test4", body: "content4", user_id: @user4.id)
@post5 = Post.create!(title: "test5", body: "content5", user_id: @user5.id)

Comment.create!(post_id: @post1.id, body: "Commented", user_id: @user1.id)
Comment.create!(post_id: @post2.id, body: "Commented", user_id: @user2.id)
Comment.create!(post_id: @post3.id, body: "Commented", user_id: @user3.id)
Comment.create!(post_id: @post4.id, body: "Commented", user_id: @user4.id)
Comment.create!(post_id: @post5.id, body: "Commented", user_id: @user5.id)

Like.create!(user_id: @user5.id, post_id: @post1.id)
Like.create!(user_id: @user4.id, post_id: @post2.id)
Like.create!(user_id: @user3.id, post_id: @post3.id)
Like.create!(user_id: @user2.id, post_id: @post4.id)
Like.create!(user_id: @user1.id, post_id: @post5.id)

Friendship.create!(requestor_id: @user1.id, requestee_id: @user5.id)
Friendship.create!(requestor_id: @user2.id, requestee_id: @user3.id)
Friendship.create!(requestor_id: @user3.id, requestee_id: @user4.id)
Friendship.create!(requestor_id: @user4.id, requestee_id: @user2.id)
Friendship.create!(requestor_id: @user5.id, requestee_id: @user1.id)
